- src/SpurClient.php
We're doing everything under the update function now.
> Change move to update

- src/SpurClient.php
The Spur API now allows worker claims.
This is a tool for importing workers and claiming them as your team member.
> Update for worker claims

- src/SpurClient.php
For SW-177
https://spurjob.atlassian.net/browse/SW-177
> SW-177: Weekly pay for workplace users

- src/SpurClient.php
This PR adds an SDK end point to get worker on-boarding progress.
issue: https://spurjob.atlassian.net/browse/SW-221
> SW-221: add worker on-boarding progress.

- src/SpurClient.php
This PR adds the support to the sdk for adding shift tips.
issue: https://spurjob.atlassian.net/browse/SW-190
> SW-190: Add shift tips method

- src/SpurClient.php
issue: https://spurjob.atlassian.net/browse/SW-254
> SW-254: Add rate validation endpoint

- src/SpurClient.php
This PR adds the API support for bulk tipping shifts.
https://spurjob.atlassian.net/browse/SW-271
> SW-271: add bulk shift tips endpoint

- src/SpurClient.php
https://spurjob.atlassian.net/browse/SW-221
This PR adds support for the new API end point to fetch all workers on-boarding-progress
> SW-221: add endpoint for bulk progress

- src/SpurClient.php
https://spurjob.atlassian.net/browse/PLAT-87
> PLAT-87: add support for getting employers options

- src/SpurClient.php
https://spurjob.atlassian.net/browse/PLAT-203
requires https://github.com/spurjobs/spur/pull/4351
> PLAT-203: add employer validation check for new workers

- src/SpurClient.php
adds new api end points for 
https://spurjob.atlassian.net/browse/SW-592
> SW-592: worker and team rates

- src/SpurClient.php
https://spurjob.atlassian.net/browse/WW-328
> WW-328: endpoint to get token from the API for users

- src/SpurClient.php
https://spurjob.atlassian.net/browse/WW-303
> WW-303: update api call for team updating

- src/SpurClient.php
This PR adds rate modifier functionality to the SDK
> WW-82: add rate modifiers

- .prettierignore
- composer.json
- composer.lock
updating php version number as pre req for [WW-442](https://spurjob.atlassian.net/browse/WW-442)
> WW-442: update sdk php version to ^7.2

- src/SpurClient.php
[WW-442](https://spurjob.atlassian.net/browse/WW-442)
Add limited employee endpoints to client for use by spur web.
> WW-442-add-limited-employee-endpoints

- src/SpurClient.php
[ww-442](https://spurjob.atlassian.net/browse/WW-442?atlOrigin=eyJpIjoiZWVjOWJjZTA5MWE3NDAyODgwZDA2MWNlNDc0YzIwOTkiLCJwIjoiaiJ9)
> Ww 442 fix sdk issues

- src/SpurClient.php
https://spurwork.atlassian.net/browse/WW-587
> WW 587: add employer places endpoint to the sdk

- src/SpurClient.php
https://spurjob.atlassian.net/browse/WW-394
> WW-394: Add lock/unlock endpoints to Spur SDK

- src/SpurClient.php
[Automate intacct](https://spurwork.atlassian.net/browse/SS-277)
* and method for setting intacct amount
> SS-277 - add update intacct total

- src/SpurClient.php
[Move account agree to ToS to api](https://spurwork.atlassian.net/browse/SS-392)
* add getter for place
> SS-392 - Move account agree to ToS to api

- src/SpurClient.php
[Move non-staffed positions to api](https://spurwork.atlassian.net/browse/SS-398)
* add create/update for non-staffed teams
> SS-398 - Move non-staffed positions to api
